"""added code templates field

Revision ID: 1f240db1b5a9
Revises: 1bfcc06bb171
Create Date: 2024-11-10 22:07:35.399228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f240db1b5a9'
down_revision: Union[str, None] = '1bfcc06bb171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('template', sa.String(), nullable=True))
    op.add_column('problems', sa.Column('starter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'starter')
    op.drop_column('problems', 'template')
    # ### end Alembic commands ###
