"""changed list as mutable pickle type

Revision ID: 6bcd5294b748
Revises: fc0f3a9f75c2
Create Date: 2024-10-12 20:24:45.250370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcd5294b748'
down_revision: Union[str, None] = 'fc0f3a9f75c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'submissions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='unique')
    # ### end Alembic commands ###
