"""nullable=False for some fields

Revision ID: a16c893cf44c
Revises: b5afd22b18d1
Create Date: 2024-10-04 14:35:08.560444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a16c893cf44c'
down_revision: Union[str, None] = 'b5afd22b18d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('problems', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('problems', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('problems', 'solution',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('problems', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('problems', 'solves',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('problems', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('problems', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('problems', 'solves',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('problems', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('problems', 'solution',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('problems', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('problems', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('problems', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
