"""minor changes

Revision ID: b1dce53f6c14
Revises: a16c893cf44c
Create Date: 2024-10-04 15:06:37.955173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1dce53f6c14'
down_revision: Union[str, None] = 'a16c893cf44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'solution',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'solution',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
