"""small changes

Revision ID: c2e838ca26f3
Revises: 2ed22e952dac
Create Date: 2024-10-04 12:42:48.055010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e838ca26f3'
down_revision: Union[str, None] = '2ed22e952dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('updated_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'updated_at')
    # ### end Alembic commands ###
